### ISSUE TITLE
Broken sea

### ISSUE THREAD

**Issue by Commandcracker** [unicornpkg/wing#12]
**Describe the bug**
The sea archive is malformed.

**To Reproduce**
1. `wget run https://unicornpkg.github.io/wing/install.lua`

**Screenshots**
![grafik](https://github.com/unicornpkg/wing/assets/49335821/05503f41-6e7b-4e1a-9c69-bb8812709ee9)

**Environment (please complete the following information):**
- Emulator or mod (including version): CraftOS-PC 2.7.3 
- OS: Windows
- Program hash or version: 1684639720, 1684642385

**Comment by tomodachi94** [comment]
This is an upstream bug in imgtool-rs, see https://github.com/walksanatora/imgtool-rs/issues/2
