### ISSUE TITLE
Installer broken

### ISSUE THREAD

**Issue by tomodachi94** [unicornpkg/wing#13]
**Describe the bug**
See title

**To Reproduce**
1. Go to install instructions
2. Download provided URL and execute it
3. See error

**Expected behavior**
It should install libunicornpkg and the CLI.

**Screenshots**

**Environment (please complete the following information):**
- Emulator or mod (including version): CraftOS-PC 2.7.5
- OS: [e.g. Windows] N/A
- ROM version: Unknown
- Program hash or version: Latest

**Additional context**

**Comment by Commandcracker** [comment]
Resolved after bfbc3535cf92720199bd18538d00819f92d1cc18 6b724cf285f15d7a13199c486189ac1f799d0d32 8b478e8f043c61dc8fa4e744348abb242effe18d
