### ISSUE TITLE
Ref libunicornpkg from tag

### ISSUE THREAD

**Issue by Commandcracker** [unicornpkg/wing#9]
the installer should install libunicornpkg from unicornpkg/libunicornpkg.
the installer should ref to a libunicornpkg tag (v1.0.0)

**Comment by tomodachi94** [comment]
I'll work on this later, once I've got a release out for the CLI tools.

**Comment by tomodachi94** [comment]
The prototype for this is in `install-beta.lua`; I'm dogfooding unicornpkg to install unicornpkg.

**Comment by tomodachi94** [comment]
Irrelevant with the new build system.
